test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@adminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
