security:
    # cf site http://symfony.com/doc/current/security/entity_provider.html#security-crete-user-entity
    encoders:
        adminBundle\Entity\User:
            algorithm: bcrypt
            cost: 13 #nb de boucle pour encoder
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: adminBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            provider: our_db_provider
            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: security.login
                check_path: security.login
                default_target_path: accueil
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
                path: security.logout
                target: accueil

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: /admin, roles: ROLE_ADMIN }
            - { path: /public/client, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER