# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.twig.extension:
        class: adminBundle\Twig\AppExtension
        arguments: [ '@doctrine', '@twig']
        tags:
            - { name: twig.extension }

    admin.subscriber.category.form:
        class: adminBundle\Subscriber\CategoryFormSubscriber
        tags:
            - { name: kernel.event_subscriber}

    admin.subscriber.signup.form:
            class: adminBundle\Subscriber\SignUpFormSubscriber
            tags:
                - { name: kernel.event_subscriber}

    admin.subscriber.kernel.events:
                class: adminBundle\Subscriber\KernelEventsSubscriber
                arguments: [ '@twig', '@session' ]
                tags:
                    - { name: kernel.event_subscriber}

    admin.services.utils.string:
        class: adminBundle\Services\Utils\StringService

    admin.services.upload:
        class: adminBundle\Services\UploadService
        arguments: ['@admin.services.utils.string', '%upload_dir%']

    admin.services.deleteimg:
        class: adminBundle\Services\DeleteImgService
        arguments: ['%upload_dir%']

    admin.listener.product:
        class: adminBundle\Listener\ProductListener
        arguments: ['@admin.services.upload', '@admin.services.deleteimg', '%default_img%']
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.listener.categorie:
        class: adminBundle\Listener\CategorieListener
        arguments: ['@admin.services.upload', '@admin.services.deleteimg', '%default_img%']
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.listener.user:
            class: adminBundle\Listener\UserListener
            arguments: ['@admin.services.upload', '@admin.services.deleteimg', '%default_img%']
            tags:
                - { name: doctrine.orm.entity_listener }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension}