<?php

namespace adminBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    //Autre méthode plus courte
    public function findBrand(){
        //Le paramètre product est un alias
        $results = $this->createQueryBuilder('brand')//equivalent à un findAll()
        ->getQuery()
            ->getResult();
        die(dump($results));
        return $results;
    }
}
