<?php

namespace adminBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function nbCat() {

        $query = $this->getEntityManager()
            ->createQuery('
                    	  SELECT COUNT(cat)
                          FROM adminBundle:Categorie AS cat
                    ');

        return $query->getSingleScalarResult();
    }

    public function nbCatActive($statut) {

        $query = $this->getEntityManager()
            ->createQuery('
                    	  SELECT COUNT(cat)
                          FROM adminBundle:Categorie AS cat
                          WHERE cat.active = :statut
                    ')->setParameters(['statut' => $statut]);

        die(dump($query->getSingleScalarResult()));

        return $query->getSingleScalarResult();
    }

    public function nbCatActiveAndNot() {

        $query = $this->getEntityManager()
            ->createQuery('
                    	  SELECT COUNT(cat)
                          FROM adminBundle:Categorie AS cat
                          GROUP BY cat.active
                    ');

        die(dump($query->getSingleScalarResult()));

        return $query->getSingleScalarResult();
    }

    public function myFindProduction($nbProductPerPage, $offset) {
        $results = $this
            ->createQueryBuilder('c')
            ->setFirstResult($offset)
            ->setMaxResults($nbProductPerPage)
            ->getQuery()
            ->getResult();
        return $results;
    }



}
